# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Opentelekomcloud


class _Api(_Opentelekomcloud):
    _type = "api"
    _icon_dir = "resources/opentelekomcloud/api"


class ApiGateway(_Api):
    _icon = "api-gateway.png"


# Aliases
