# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Opentelekomcloud


class _Compute(_Opentelekomcloud):
    _type = "compute"
    _icon_dir = "resources/opentelekomcloud/compute"


class As(_Compute):
    _icon = "as.png"


class BareMetal(_Compute):
    _icon = "bare-metal.png"


class Cce(_Compute):
    _icon = "cce.png"


class DedicatedHost(_Compute):
    _icon = "dedicated-host.png"


class Ecs(_Compute):
    _icon = "ecs.png"


class Gpu(_Compute):
    _icon = "gpu.png"


class Ims(_Compute):
    _icon = "ims.png"


# Aliases
