# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Opentelekomcloud


class _Dataanalysis(_Opentelekomcloud):
    _type = "dataanalysis"
    _icon_dir = "resources/opentelekomcloud/dataanalysis"


class Css(_Dataanalysis):
    _icon = "css.png"


class Dis(_Dataanalysis):
    _icon = "dis.png"


class Dws(_Dataanalysis):
    _icon = "dws.png"


class Modelarts(_Dataanalysis):
    _icon = "modelarts.png"


class Mrs(_Dataanalysis):
    _icon = "mrs.png"


# Aliases
