# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Opentelekomcloud


class _Database(_Opentelekomcloud):
    _type = "database"
    _icon_dir = "resources/opentelekomcloud/database"


class Dds(_Database):
    _icon = "dds.png"


class Distributedcache(_Database):
    _icon = "distributedcache.png"


class Rds(_Database):
    _icon = "rds.png"


# Aliases
