# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Opentelekomcloud


class _General(_Opentelekomcloud):
    _type = "general"
    _icon_dir = "resources/opentelekomcloud/general"


class Eu(_General):
    _icon = "eu.png"


class Openstack(_General):
    _icon = "openstack.png"


class Opentelekomcloud(_General):
    _icon = "opentelekomcloud.png"


class Tsystems(_General):
    _icon = "tsystems.png"


# Aliases
