# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Opentelekomcloud


class _Management(_Opentelekomcloud):
    _type = "management"
    _icon_dir = "resources/opentelekomcloud/management"


class Coudeye(_Management):
    _icon = "coudeye.png"


class Cts(_Management):
    _icon = "cts.png"


class Dms(_Management):
    _icon = "dms.png"


class Heat(_Management):
    _icon = "heat.png"


class Maas(_Management):
    _icon = "maas.png"


class Smns(_Management):
    _icon = "smns.png"


class Tagservice(_Management):
    _icon = "tagservice.png"


# Aliases
