# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Opentelekomcloud


class _Network(_Opentelekomcloud):
    _type = "network"
    _icon_dir = "resources/opentelekomcloud/network"


class Cdn(_Network):
    _icon = "cdn.png"


class DirectConnect(_Network):
    _icon = "direct-connect.png"


class Dns(_Network):
    _icon = "dns.png"


class ExternalIpAddresses(_Network):
    _icon = "external-ip-addresses.png"


class FirewallRules(_Network):
    _icon = "firewall-rules.png"


class LoadBalancing(_Network):
    _icon = "load-balancing.png"


class NatGateway(_Network):
    _icon = "nat-gateway.png"


class Network(_Network):
    _icon = "network.png"


class Router(_Network):
    _icon = "router.png"


class Routes(_Network):
    _icon = "routes.png"


class SecurityGroup(_Network):
    _icon = "security-group.png"


class Vfw(_Network):
    _icon = "vfw.png"


class VpcPeering(_Network):
    _icon = "vpc-peering.png"


class Vpc(_Network):
    _icon = "vpc.png"


class Vpn(_Network):
    _icon = "vpn.png"


# Aliases
