# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Opentelekomcloud


class _Operations(_Opentelekomcloud):
    _type = "operations"
    _icon_dir = "resources/opentelekomcloud/operations"


class Aom(_Operations):
    _icon = "aom.png"


# Aliases
