# This module is automatically generated by autogen.sh. DO NOT EDIT.

from . import _Opentelekomcloud


class _Security(_Opentelekomcloud):
    _type = "security"
    _icon_dir = "resources/opentelekomcloud/security"


class Antiddos(_Security):
    _icon = "antiddos.png"


class Iam(_Security):
    _icon = "iam.png"


class KeyManagementService(_Security):
    _icon = "key-management-service.png"


class Waf(_Security):
    _icon = "waf.png"


# Aliases
